### ISSUE TITLE
Installer script logo is missing

### ISSUE THREAD

**Issue by Zefiro** [LedFx/ledfx-tools#4]
While reading through your setup script, I noticed these lines:

```
  # Pretty logo so we can verify it's us.
  curl -sSL https://install.ledfx.app/ledfxrainbow.out | cat
  # Could probably do something more productive here to display the logo, but oh well.
  sleep 3
```

However, the referenced file - which forwards to https://raw.githubusercontent.com/LedFx/ledfx-tools/main/installers/ledfx-pypi.shledfxrainbow.out - does not exist, and according to commit history, never existed in this repository.

**Comment by shauneccles** [comment]
Fixed, thanks.
